name: Checkout

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: build and test
      run: |
        npm install
        npm test

  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}


      - name: build image 
        run: docker image build -t levent2607/cicd-demo .

      - name: push image
        run: docker image push levent2607/cicd-demo:latest  

  bring_live:
    runs-on: aws-ec2

      steps:
        - name: fetch image
          run: docker image pull levent2607/cicd-demo:latest

        - name: remove old container
          run: docker container rm -f cicd-demo 

        - name: run new container  
          run: docker container run -d -p 3000:3000 --name cicd-demo levent2607/cicd-demo:latest       
