name: Checkout

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: build and test
      run: |
        npm install
        npm test
